version: '3.4'
services:
    prnportal:
        image: ${DOCKER_REGISTRY-}prnportal
        build:
            context: .
            dockerfile: EPRN.Portal/Dockerfile

    wasteapi:
        image: ${DOCKER_REGISTRY-}wasteapi
        build:
            context: .
            dockerfile: EPRN.Waste.API/Dockerfile

    prnapi:
        image: ${DOCKER_REGISTRY-}prnapi
        build:
            context: .
            dockerfile: EPRN.PRNS.API/Dockerfile