version: '3.4'

services:
  eprn.waste.api:
    image: ${DOCKER_REGISTRY-}eprnwasteapi
    build:
      context: .
      dockerfile: EPRN.Waste.API/Dockerfile

  eprn.portal:
    image: ${DOCKER_REGISTRY-}eprnportal
    build:
      context: .
      dockerfile: EPRN.Portal/Dockerfile

