//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPRN.Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccredidationLimitResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccredidationLimitResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPRN.Portal.Resources.AccredidationLimitResources", typeof(AccredidationLimitResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re about to go over your accredidation limit.
        /// </summary>
        public static string LimitAlertTitle {
            get {
                return ResourceManager.GetString("LimitAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can continue creating this PRN, but must .
        /// </summary>
        public static string Line1_Part1 {
            get {
                return ResourceManager.GetString("Line1_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pay an extra accredidation fee .
        /// </summary>
        public static string Line1_Part2 {
            get {
                return ResourceManager.GetString("Line1_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to within 28 days..
        /// </summary>
        public static string Line1_Part3 {
            get {
                return ResourceManager.GetString("Line1_Part3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve entered &lt;&lt;newTonnageEntered&gt;&gt; tonnes. This will exceed your accredidation limit by &lt;&lt;exceedLimitBy&gt;&gt; tonnes..
        /// </summary>
        public static string Line2 {
            get {
                return ResourceManager.GetString("Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current accredidation limit: &lt;&lt;currentAccredidationLimit&gt;&gt; tonnes.
        /// </summary>
        public static string Line3 {
            get {
                return ResourceManager.GetString("Line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total PRNs issued to date: &lt;&lt;totalPrnTonnageToDate&gt;&gt; tonnes.
        /// </summary>
        public static string Line4 {
            get {
                return ResourceManager.GetString("Line4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accredidation Limit Alert.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
