//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPRN.Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreatePrnPern {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreatePrnPern() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPRN.Portal.Resources.CreatePrnPern", typeof(CreatePrnPern).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accreditations for:.
        /// </summary>
        public static string AccreditationsFor {
            get {
                return ResourceManager.GetString("AccreditationsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aluminium.
        /// </summary>
        public static string Aluminium {
            get {
                return ResourceManager.GetString("Aluminium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough balance to create a PERN. A PERN must be a whole tonnage.
        /// </summary>
        public static string BalanceWarningPern {
            get {
                return ResourceManager.GetString("BalanceWarningPern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough balance to create a PRN. A PRN must be a whole tonnage.
        /// </summary>
        public static string BalanceWarningPrn {
            get {
                return ResourceManager.GetString("BalanceWarningPrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough balance to create a PRN/PERN. A PRN/PERN must be a whole tonnage.
        /// </summary>
        public static string BalanceWarningPrnPern {
            get {
                return ResourceManager.GetString("BalanceWarningPrnPern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string ChooseLink {
            get {
                return ResourceManager.GetString("ChooseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an accreditation to create your PERN..
        /// </summary>
        public static string DescriptionPartOnePern {
            get {
                return ResourceManager.GetString("DescriptionPartOnePern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an accreditation to create your PRN..
        /// </summary>
        public static string DescriptionPartOnePrn {
            get {
                return ResourceManager.GetString("DescriptionPartOnePrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an accreditation to create your PRN/PERN..
        /// </summary>
        public static string DescriptionPartOnePrnPern {
            get {
                return ResourceManager.GetString("DescriptionPartOnePrnPern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round the balance to the nearest whole tonne to determine the amount available for creating the PERN..
        /// </summary>
        public static string DescriptionPartTwoPern {
            get {
                return ResourceManager.GetString("DescriptionPartTwoPern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round the balance to the nearest whole tonne to determine the amount available for creating the PRN..
        /// </summary>
        public static string DescriptionPartTwoPrn {
            get {
                return ResourceManager.GetString("DescriptionPartTwoPrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round the balance to the nearest whole tonne to determine the amount available for creating the PRN/PERN..
        /// </summary>
        public static string DescriptionPartTwoPrnPern {
            get {
                return ResourceManager.GetString("DescriptionPartTwoPrnPern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter.
        /// </summary>
        public static string Exporter {
            get {
                return ResourceManager.GetString("Exporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting.
        /// </summary>
        public static string ExportingHeading {
            get {
                return ResourceManager.GetString("ExportingHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By.
        /// </summary>
        public static string FilterBy {
            get {
                return ResourceManager.GetString("FilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass.
        /// </summary>
        public static string Glass {
            get {
                return ResourceManager.GetString("Glass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of draft PERNs.
        /// </summary>
        public static string NumberOfDraftPerns {
            get {
                return ResourceManager.GetString("NumberOfDraftPerns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of draft PRNs.
        /// </summary>
        public static string NumberOfDraftPrns {
            get {
                return ResourceManager.GetString("NumberOfDraftPrns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper/board.
        /// </summary>
        public static string PaperBoard {
            get {
                return ResourceManager.GetString("PaperBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprocessing.
        /// </summary>
        public static string ReprocessingHeading {
            get {
                return ResourceManager.GetString("ReprocessingHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprocessor.
        /// </summary>
        public static string Reprocessor {
            get {
                return ResourceManager.GetString("Reprocessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel.
        /// </summary>
        public static string Steel {
            get {
                return ResourceManager.GetString("Steel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a PERN.
        /// </summary>
        public static string TitlePern {
            get {
                return ResourceManager.GetString("TitlePern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a PRN.
        /// </summary>
        public static string TitlePrn {
            get {
                return ResourceManager.GetString("TitlePrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create PRN/PERN.
        /// </summary>
        public static string TitlePrnPern {
            get {
                return ResourceManager.GetString("TitlePrnPern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonnage available to create PERNs.
        /// </summary>
        public static string TonnageAvailablePern {
            get {
                return ResourceManager.GetString("TonnageAvailablePern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonnage available to create PRNs.
        /// </summary>
        public static string TonnageAvailablePrn {
            get {
                return ResourceManager.GetString("TonnageAvailablePrn", resourceCulture);
            }
        }
    }
}
