//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPRN.Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CYAResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CYAResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPRN.Portal.Resources.CYAResources", typeof(CYAResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baled with wire.
        /// </summary>
        public static string BaledWithWire {
            get {
                return ResourceManager.GetString("BaledWithWire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ChangeLinkText {
            get {
                return ResourceManager.GetString("ChangeLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create waste record.
        /// </summary>
        public static string CreateBtn {
            get {
                return ResourceManager.GetString("CreateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the material type?.
        /// </summary>
        public static string MaterialType {
            get {
                return ResourceManager.GetString("MaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month the waste was received.
        /// </summary>
        public static string MonthReceived {
            get {
                return ResourceManager.GetString("MonthReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the waste was exported.
        /// </summary>
        public static string MonthWasteExported {
            get {
                return ResourceManager.GetString("MonthWasteExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note (optional).
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your answers before creating this waste record.
        /// </summary>
        public static string ReprocessorResentPageHeader {
            get {
                return ResourceManager.GetString("ReprocessorResentPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address of the reprocessor where the waste was sent.
        /// </summary>
        public static string ReprocessorWhereWasteSentAddress {
            get {
                return ResourceManager.GetString("ReprocessorWhereWasteSentAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the reprocessor where the waste was sent.
        /// </summary>
        public static string ReprocessorWhereWasteSentName {
            get {
                return ResourceManager.GetString("ReprocessorWhereWasteSentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your answers before creating this waste record.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonnage adjusted for deductions.
        /// </summary>
        public static string TonnageAdjusted {
            get {
                return ResourceManager.GetString("TonnageAdjusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonnage of waste.
        /// </summary>
        public static string TonnageOfWaste {
            get {
                return ResourceManager.GetString("TonnageOfWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of waste.
        /// </summary>
        public static string TypeOfWaste {
            get {
                return ResourceManager.GetString("TypeOfWaste", resourceCulture);
            }
        }
    }
}
