//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPRN.Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CYAResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CYAResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPRN.Portal.Resources.CYAResources", typeof(CYAResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was the .
        /// </summary>
        public static string BaledPartOne {
            get {
                return ResourceManager.GetString("BaledPartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to baled with wire.
        /// </summary>
        public static string BaledPartTwo {
            get {
                return ResourceManager.GetString("BaledPartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ChangeLinkText {
            get {
                return ResourceManager.GetString("ChangeLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm and continue.
        /// </summary>
        public static string ConfirmAndContinueBtn {
            get {
                return ResourceManager.GetString("ConfirmAndContinueBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During which month was the material supplied on?.
        /// </summary>
        public static string DuringWhichMonth {
            get {
                return ResourceManager.GetString("DuringWhichMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the material type?.
        /// </summary>
        public static string MaterialType {
            get {
                return ResourceManager.GetString("MaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the material sub type?.
        /// </summary>
        public static string SubType {
            get {
                return ResourceManager.GetString("SubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your answers.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tonnes.
        /// </summary>
        public static string Tonnes {
            get {
                return ResourceManager.GetString("Tonnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the total tonnes of .
        /// </summary>
        public static string TonnesReceivedPartOne {
            get {
                return ResourceManager.GetString("TonnesReceivedPartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to received.
        /// </summary>
        public static string TonnesReceivedPartTwo {
            get {
                return ResourceManager.GetString("TonnesReceivedPartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste received details.
        /// </summary>
        public static string WasteReceivedDetails {
            get {
                return ResourceManager.GetString("WasteReceivedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste type and weight details.
        /// </summary>
        public static string WasteTypeAndWeight {
            get {
                return ResourceManager.GetString("WasteTypeAndWeight", resourceCulture);
            }
        }
    }
}
