//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPRN.Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GovFrontEndTextOverrideResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GovFrontEndTextOverrideResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPRN.Portal.Resources.GovFrontEndTextOverrideResources", typeof(GovFrontEndTextOverrideResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have 0 characters remaining.
        /// </summary>
        public static string charactersAtLimit {
            get {
                return ResourceManager.GetString("charactersAtLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have %{count} character too many.
        /// </summary>
        public static string charactersOverLimitOne {
            get {
                return ResourceManager.GetString("charactersOverLimitOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have %{count} characters too many.
        /// </summary>
        public static string charactersOverLimitOther {
            get {
                return ResourceManager.GetString("charactersOverLimitOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have %{count} character remaining.
        /// </summary>
        public static string charactersUnderLimitOne {
            get {
                return ResourceManager.GetString("charactersUnderLimitOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have %{count} characters remaining.
        /// </summary>
        public static string charactersUnderLimitOther {
            get {
                return ResourceManager.GetString("charactersUnderLimitOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string hideSection {
            get {
                return ResourceManager.GetString("hideSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string showSection {
            get {
                return ResourceManager.GetString("showSection", resourceCulture);
            }
        }
    }
}
