//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPRN.Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomePageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPRN.Portal.Resources.HomePageResources", typeof(HomePageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeLink {
            get {
                return ResourceManager.GetString("HomeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and manage users.
        /// </summary>
        public static string HomePage_Account_Description {
            get {
                return ResourceManager.GetString("HomePage_Account_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new user.
        /// </summary>
        public static string HomePage_Account_Link_CreateUser {
            get {
                return ResourceManager.GetString("HomePage_Account_Link_CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View my account details.
        /// </summary>
        public static string HomePage_Account_Link_DetailUser {
            get {
                return ResourceManager.GetString("HomePage_Account_Link_DetailUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage a user.
        /// </summary>
        public static string HomePage_Account_Link_ManageUser {
            get {
                return ResourceManager.GetString("HomePage_Account_Link_ManageUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string HomePage_Account_Title {
            get {
                return ResourceManager.GetString("HomePage_Account_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply for accreditation, check your status and view all applications.
        /// </summary>
        public static string HomePage_Accredidation_Description {
            get {
                return ResourceManager.GetString("HomePage_Accredidation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply for accredidation.
        /// </summary>
        public static string HomePage_Accredidation_Link_ApplyForAccredidation {
            get {
                return ResourceManager.GetString("HomePage_Accredidation_Link_ApplyForAccredidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My accredidations.
        /// </summary>
        public static string HomePage_Accredidation_Link_MyAccredidations {
            get {
                return ResourceManager.GetString("HomePage_Accredidation_Link_MyAccredidations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all applications.
        /// </summary>
        public static string HomePage_Accredidation_Link_ViewApplications {
            get {
                return ResourceManager.GetString("HomePage_Accredidation_Link_ViewApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accredidation.
        /// </summary>
        public static string HomePage_Accredidation_Title {
            get {
                return ResourceManager.GetString("HomePage_Accredidation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create PERNs, edit drafts and view sent PERNs.
        /// </summary>
        public static string HomePage_ManagePern_Description {
            get {
                return ResourceManager.GetString("HomePage_ManagePern_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a PERN.
        /// </summary>
        public static string HomePage_ManagePern_Link_CreatePern {
            get {
                return ResourceManager.GetString("HomePage_ManagePern_Link_CreatePern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and edit draft PERNS.
        /// </summary>
        public static string HomePage_ManagePern_Link_ViewEditDraftPerns {
            get {
                return ResourceManager.GetString("HomePage_ManagePern_Link_ViewEditDraftPerns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View sent PERNS.
        /// </summary>
        public static string HomePage_ManagePern_Link_ViewSentPerns {
            get {
                return ResourceManager.GetString("HomePage_ManagePern_Link_ViewSentPerns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage PERN.
        /// </summary>
        public static string HomePage_ManagePern_Title {
            get {
                return ResourceManager.GetString("HomePage_ManagePern_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create PRNs, edit drafts and view sent PRNs.
        /// </summary>
        public static string HomePage_ManagePrn_Description {
            get {
                return ResourceManager.GetString("HomePage_ManagePrn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a PRN.
        /// </summary>
        public static string HomePage_ManagePrn_Link_CreatePrn {
            get {
                return ResourceManager.GetString("HomePage_ManagePrn_Link_CreatePrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and edit draft PRNs.
        /// </summary>
        public static string HomePage_ManagePrn_Link_ViewEditDraftPrn {
            get {
                return ResourceManager.GetString("HomePage_ManagePrn_Link_ViewEditDraftPrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View sent PRNs.
        /// </summary>
        public static string HomePage_ManagePrn_Link_ViewSentPrns {
            get {
                return ResourceManager.GetString("HomePage_ManagePrn_Link_ViewSentPrns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage PRN.
        /// </summary>
        public static string HomePage_ManagePrn_Title {
            get {
                return ResourceManager.GetString("HomePage_ManagePrn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create PRNs/PERNs, edit drafts and view sent PRNs/PERNs.
        /// </summary>
        public static string HomePage_ManagePrnPern_Description {
            get {
                return ResourceManager.GetString("HomePage_ManagePrnPern_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a PRN/PERN.
        /// </summary>
        public static string HomePage_ManagePrnPern_Link_CreatePrnPern {
            get {
                return ResourceManager.GetString("HomePage_ManagePrnPern_Link_CreatePrnPern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and edit draft PRNs/PERNS.
        /// </summary>
        public static string HomePage_ManagePrnPern_Link_ViewEditDraftPrnsPerns {
            get {
                return ResourceManager.GetString("HomePage_ManagePrnPern_Link_ViewEditDraftPrnsPerns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View sent PRNs/PERNS.
        /// </summary>
        public static string HomePage_ManagePrnPern_Link_ViewSentPrnPerns {
            get {
                return ResourceManager.GetString("HomePage_ManagePrnPern_Link_ViewSentPrnPerns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage PRN/PERN.
        /// </summary>
        public static string HomePage_ManagePrnPern_Title {
            get {
                return ResourceManager.GetString("HomePage_ManagePrnPern_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit quarterly returns.
        /// </summary>
        public static string HomePage_Returns_Description {
            get {
                return ResourceManager.GetString("HomePage_Returns_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit a return.
        /// </summary>
        public static string HomePage_Returns_Link_SubmitReturn {
            get {
                return ResourceManager.GetString("HomePage_Returns_Link_SubmitReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns.
        /// </summary>
        public static string HomePage_Returns_Title {
            get {
                return ResourceManager.GetString("HomePage_Returns_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste - Home.
        /// </summary>
        public static string HomePage_Title {
            get {
                return ResourceManager.GetString("HomePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record waste and view waste records.
        /// </summary>
        public static string HomePage_Waste_Description {
            get {
                return ResourceManager.GetString("HomePage_Waste_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Waste.
        /// </summary>
        public static string HomePage_Waste_Link_RecordWaste {
            get {
                return ResourceManager.GetString("HomePage_Waste_Link_RecordWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View, edit, download or delete waste records.
        /// </summary>
        public static string HomePage_Waste_Link_ViewEditDownloadDelete {
            get {
                return ResourceManager.GetString("HomePage_Waste_Link_ViewEditDownloadDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste.
        /// </summary>
        public static string HomePage_Waste_Title {
            get {
                return ResourceManager.GetString("HomePage_Waste_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record your waste, manage your PRNs and submit your returns.
        /// </summary>
        public static string HomePage_WasteManagement_Description {
            get {
                return ResourceManager.GetString("HomePage_WasteManagement_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage a PRN.
        /// </summary>
        public static string HomePage_WasteManagement_Link_ManageAPrn {
            get {
                return ResourceManager.GetString("HomePage_WasteManagement_Link_ManageAPrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record waste.
        /// </summary>
        public static string HomePage_WasteManagement_Link_RecordWaste {
            get {
                return ResourceManager.GetString("HomePage_WasteManagement_Link_RecordWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit a return.
        /// </summary>
        public static string HomePage_WasteManagement_Link_SubmitAReturn {
            get {
                return ResourceManager.GetString("HomePage_WasteManagement_Link_SubmitAReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and edit records.
        /// </summary>
        public static string HomePage_WasteManagement_Link_ViewEditRecords {
            get {
                return ResourceManager.GetString("HomePage_WasteManagement_Link_ViewEditRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Management.
        /// </summary>
        public static string HomePage_WasteManagement_Title {
            get {
                return ResourceManager.GetString("HomePage_WasteManagement_Title", resourceCulture);
            }
        }
    }
}
