//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPRN.Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MasterResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MasterResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPRN.Portal.Resources.MasterResources", typeof(MasterResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCEPTED.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWAITING ACCEPTANCE.
        /// </summary>
        public static string AwaitingAcceptance {
            get {
                return ResourceManager.GetString("AwaitingAcceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWAITING CANCELLATION.
        /// </summary>
        public static string AwaitingCancellation {
            get {
                return ResourceManager.GetString("AwaitingCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCELLED.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ContinueBtn {
            get {
                return ResourceManager.GetString("ContinueBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a &lt;PRNTYPE&gt; for:.
        /// </summary>
        public static string CreateWithReplace {
            get {
                return ResourceManager.GetString("CreateWithReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid numerical value.
        /// </summary>
        public static string MustBeANumber {
            get {
                return ResourceManager.GetString("MustBeANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cymraeg.
        /// </summary>
        public static string OppositeLanguage {
            get {
                return ResourceManager.GetString("OppositeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERN.
        /// </summary>
        public static string PERN {
            get {
                return ResourceManager.GetString("PERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRN.
        /// </summary>
        public static string PRN {
            get {
                return ResourceManager.GetString("PRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording for:.
        /// </summary>
        public static string RecordingFor {
            get {
                return ResourceManager.GetString("RecordingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REJECTED.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip question.
        /// </summary>
        public static string SkipQuestionLink {
            get {
                return ResourceManager.GetString("SkipQuestionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem.
        /// </summary>
        public static string SummaryError {
            get {
                return ResourceManager.GetString("SummaryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;UNKNOWN WASTE TYPE&gt;.
        /// </summary>
        public static string UnknownWasteType {
            get {
                return ResourceManager.GetString("UnknownWasteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
