//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPRN.Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WasteSubTypesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WasteSubTypesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPRN.Portal.Resources.WasteSubTypesResources", typeof(WasteSubTypesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade 1.04.01.
        /// </summary>
        public static string _1_grade_1_04_01 {
            get {
                return ResourceManager.GetString("1-grade-1.04.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade 1.04.02.
        /// </summary>
        public static string _1_grade_1_04_02 {
            get {
                return ResourceManager.GetString("1-grade-1.04.02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grades 1.04.00, 1.05.00 &amp; 1.05.01.
        /// </summary>
        public static string _1_grades_1_04_00_1_05_00_1_05_01 {
            get {
                return ResourceManager.GetString("1-grades-1.04.00-1.05.00-1.05.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string _1_other {
            get {
                return ResourceManager.GetString("1-other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted mixed paper/board.
        /// </summary>
        public static string _1_sorted_mixed_paper_board {
            get {
                return ResourceManager.GetString("1-sorted-mixed-paper/board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsorted mixed paper/board.
        /// </summary>
        public static string _1_unsorted_mixed_paper_board {
            get {
                return ResourceManager.GetString("1-unsorted-mixed paper/board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade 1.04.01.
        /// </summary>
        public static string _2_grade_1_04_01 {
            get {
                return ResourceManager.GetString("2-grade-1.04.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade 1.04.02.
        /// </summary>
        public static string _2_grade_1_04_02 {
            get {
                return ResourceManager.GetString("2-grade-1.04.02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grades 1.04.00, 1.05.00 &amp; 1.05.01.
        /// </summary>
        public static string _2_grades_1_04_00_1_05_00_1_05_01 {
            get {
                return ResourceManager.GetString("2-grades-1.04.00-1.05.00-1.05.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string _2_other {
            get {
                return ResourceManager.GetString("2-other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted mixed paper/board.
        /// </summary>
        public static string _2_sorted_mixed_paper_board {
            get {
                return ResourceManager.GetString("2-sorted-mixed-paper/board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsorted mixed paper.board.
        /// </summary>
        public static string _2_unsorted_mixed_paper_board {
            get {
                return ResourceManager.GetString("2-unsorted-mixed-paper.board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% packaging.
        /// </summary>
        public static string _3_100__packaging {
            get {
                return ResourceManager.GetString("3-100%-packaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string _3_other {
            get {
                return ResourceManager.GetString("3-other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% packaging.
        /// </summary>
        public static string _4_100__packaging {
            get {
                return ResourceManager.GetString("4-100%-packaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string _4_other {
            get {
                return ResourceManager.GetString("4-other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cans and associated packaging.
        /// </summary>
        public static string _5_cans_and_associated_packaging {
            get {
                return ResourceManager.GetString("5-cans-and-associated-packaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted from IBA.
        /// </summary>
        public static string _5_extracted_from_iba {
            get {
                return ResourceManager.GetString("5-extracted-from-iba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string _5_other {
            get {
                return ResourceManager.GetString("5-other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1+2 mixed.
        /// </summary>
        public static string _6_1_2_mixed {
            get {
                return ResourceManager.GetString("6-1+2-mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string _6_2 {
            get {
                return ResourceManager.GetString("6-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4C.
        /// </summary>
        public static string _6_4c {
            get {
                return ResourceManager.GetString("6-4c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4E.
        /// </summary>
        public static string _6_4e {
            get {
                return ResourceManager.GetString("6-4e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8B.
        /// </summary>
        public static string _6_8b {
            get {
                return ResourceManager.GetString("6-8b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragmentised.
        /// </summary>
        public static string _6_fragmentised {
            get {
                return ResourceManager.GetString("6-fragmentised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string _6_other {
            get {
                return ResourceManager.GetString("6-other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel cans grade 6E.
        /// </summary>
        public static string _6_steel_cans_grade_6e {
            get {
                return ResourceManager.GetString("6-steel-cans-grade-6e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDPE.
        /// </summary>
        public static string _7_hdpe {
            get {
                return ResourceManager.GetString("7-hdpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed.
        /// </summary>
        public static string _7_mixed {
            get {
                return ResourceManager.GetString("7-mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string _7_other {
            get {
                return ResourceManager.GetString("7-other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging film.
        /// </summary>
        public static string _7_packaging_film {
            get {
                return ResourceManager.GetString("7-packaging-film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PET.
        /// </summary>
        public static string _7_pet {
            get {
                return ResourceManager.GetString("7-pet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pots, tubs, trays.
        /// </summary>
        public static string _7_Pots_tubs_trays {
            get {
                return ResourceManager.GetString("7-Pots-tubs-trays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% packaging.
        /// </summary>
        public static string _8_100__packaging {
            get {
                return ResourceManager.GetString("8-100%-packaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string _8_other {
            get {
                return ResourceManager.GetString("8-other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% packaging.
        /// </summary>
        public static string _9_100__packaging {
            get {
                return ResourceManager.GetString("9-100%-packaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string _9_other {
            get {
                return ResourceManager.GetString("9-other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the percentage received.
        /// </summary>
        public static string AdjustmentPercentageRequiredMessage {
            get {
                return ResourceManager.GetString("AdjustmentPercentageRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a number between 1 and 100 (inclusive).
        /// </summary>
        public static string InvalidPercentageMessage {
            get {
                return ResourceManager.GetString("InvalidPercentageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What type of waste was it?.
        /// </summary>
        public static string MaterialSubTypeOptionsTitle {
            get {
                return ResourceManager.GetString("MaterialSubTypeOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A material sub type requires to be selected.
        /// </summary>
        public static string MissingWasteSubTypeSelectionMessage {
            get {
                return ResourceManager.GetString("MissingWasteSubTypeSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the percentage of packaging content agreed with your local agency..
        /// </summary>
        public static string OtherOptionHint {
            get {
                return ResourceManager.GetString("OtherOptionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ‘other’ if you’re accredited for a waste type not listed here..
        /// </summary>
        public static string PageSubHint {
            get {
                return ResourceManager.GetString("PageSubHint", resourceCulture);
            }
        }
    }
}
