//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPRN.Portal.Resources.PRNS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CancelledResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CancelledResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPRN.Portal.Resources.PRNS.CancelledResources", typeof(CancelledResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve emailed {0} to let them know you&apos;ve cancelled this PERN.
        /// </summary>
        public static string PERNEmailedProducerMessage {
            get {
                return ResourceManager.GetString("PERNEmailedProducerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This PERN has not been cancelled.
        /// </summary>
        public static string PERNNotCancelled {
            get {
                return ResourceManager.GetString("PERNNotCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to cancel this PERN.
        /// </summary>
        public static string PERNRequestToCancel {
            get {
                return ResourceManager.GetString("PERNRequestToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve emailed {0} to let them know you&apos;ve cancelled this PRN.
        /// </summary>
        public static string PRNEmailedProducerMessage {
            get {
                return ResourceManager.GetString("PRNEmailedProducerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This PRN has not been cancelled.
        /// </summary>
        public static string PRNNotCancelled {
            get {
                return ResourceManager.GetString("PRNNotCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to cancel this PRN.
        /// </summary>
        public static string PRNRequestToCancel {
            get {
                return ResourceManager.GetString("PRNRequestToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View sent PRNs.
        /// </summary>
        public static string ViewSentPRNs {
            get {
                return ResourceManager.GetString("ViewSentPRNs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What happens next.
        /// </summary>
        public static string WhatHappensNextMessage {
            get {
                return ResourceManager.GetString("WhatHappensNextMessage", resourceCulture);
            }
        }
    }
}
