//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPRN.Portal.Resources.PRNS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CheckYourAnswersResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CheckYourAnswersResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPRN.Portal.Resources.PRNS.CheckYourAnswersResources", typeof(CheckYourAnswersResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create another PERN.
        /// </summary>
        public static string CreateAnotherPERNButton {
            get {
                return ResourceManager.GetString("CreateAnotherPERNButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create another PRN.
        /// </summary>
        public static string CreateAnotherPRNButton {
            get {
                return ResourceManager.GetString("CreateAnotherPRNButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must complete all questions before creating this PERN.
        /// </summary>
        public static string IncompletePern {
            get {
                return ResourceManager.GetString("IncompletePern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must complete all questions before creating this PRN.
        /// </summary>
        public static string IncompletePrn {
            get {
                return ResourceManager.GetString("IncompletePrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and send this PERN.
        /// </summary>
        public static string PernButtonText {
            get {
                return ResourceManager.GetString("PernButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your answers before creating and sending this PERN.
        /// </summary>
        public static string PernHeading {
            get {
                return ResourceManager.GetString("PernHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and send this PRN.
        /// </summary>
        public static string PrnButtonText {
            get {
                return ResourceManager.GetString("PrnButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your answers before creating and sending this PRN.
        /// </summary>
        public static string PrnHeading {
            get {
                return ResourceManager.GetString("PrnHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging producer or compliance scheme.
        /// </summary>
        public static string SentTo {
            get {
                return ResourceManager.GetString("SentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your answers.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonnage amount.
        /// </summary>
        public static string TonnageAmount {
            get {
                return ResourceManager.GetString("TonnageAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of material.
        /// </summary>
        public static string TypeOfMaterial {
            get {
                return ResourceManager.GetString("TypeOfMaterial", resourceCulture);
            }
        }
    }
}
