//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPRN.Portal.Resources.PRNS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfirmationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfirmationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPRN.Portal.Resources.PRNS.ConfirmationResources", typeof(ConfirmationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create another PERN.
        /// </summary>
        public static string CreateAnotherPERNButton {
            get {
                return ResourceManager.GetString("CreateAnotherPERNButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create another PRN.
        /// </summary>
        public static string CreateAnotherPRNButton {
            get {
                return ResourceManager.GetString("CreateAnotherPRNButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download this PERN.
        /// </summary>
        public static string DownloadPERNButton {
            get {
                return ResourceManager.GetString("DownloadPERNButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download this PRN.
        /// </summary>
        public static string DownloadPRNButton {
            get {
                return ResourceManager.GetString("DownloadPRNButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must complete all questions before creating PERN.
        /// </summary>
        public static string PERNErrorMessage {
            get {
                return ResourceManager.GetString("PERNErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERN number.
        /// </summary>
        public static string PERNNumberLabel {
            get {
                return ResourceManager.GetString("PERNNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERN Confirmation.
        /// </summary>
        public static string PERNPageTitle {
            get {
                return ResourceManager.GetString("PERNPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERN sent to:.
        /// </summary>
        public static string PERNSentToLabel {
            get {
                return ResourceManager.GetString("PERNSentToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must complete all questions before creating PRN.
        /// </summary>
        public static string PRNErrorMessage {
            get {
                return ResourceManager.GetString("PRNErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRN number.
        /// </summary>
        public static string PRNNumberLabel {
            get {
                return ResourceManager.GetString("PRNNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRN Confirmation.
        /// </summary>
        public static string PRNPageTitle {
            get {
                return ResourceManager.GetString("PRNPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRN sent to:.
        /// </summary>
        public static string PRNSentToLabel {
            get {
                return ResourceManager.GetString("PRNSentToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll send you an email as soon as the producer or compliance scheme accepts or rejects this PRN.
        /// </summary>
        public static string SendEmailLabel {
            get {
                return ResourceManager.GetString("SendEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View sent PERNs.
        /// </summary>
        public static string ViewSentPERNsButton {
            get {
                return ResourceManager.GetString("ViewSentPERNsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View sent PRNs.
        /// </summary>
        public static string ViewSentPRNsButton {
            get {
                return ResourceManager.GetString("ViewSentPRNsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What happens next.
        /// </summary>
        public static string WhatHappensNextLabel {
            get {
                return ResourceManager.GetString("WhatHappensNextLabel", resourceCulture);
            }
        }
    }
}
