//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPRN.Portal.Resources.PRNS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DraftPrnsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DraftPrnsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPRN.Portal.Resources.PRNS.DraftPrnsResources", typeof(DraftPrnsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue editing.
        /// </summary>
        public static string BtnContinueEditing {
            get {
                return ResourceManager.GetString("BtnContinueEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete PERN.
        /// </summary>
        public static string BtnDelete_Exporter {
            get {
                return ResourceManager.GetString("BtnDelete_Exporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete PRN.
        /// </summary>
        public static string BtnDelete_Reprocessor {
            get {
                return ResourceManager.GetString("BtnDelete_Reprocessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft {0} has been deleted.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View draft PERNs.
        /// </summary>
        public static string Heading_Exporter {
            get {
                return ResourceManager.GetString("Heading_Exporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View draft PRNs.
        /// </summary>
        public static string Heading_Reprocessor {
            get {
                return ResourceManager.GetString("Heading_Reprocessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        public static string Important {
            get {
                return ResourceManager.GetString("Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View, edit or delete a draft PERN.
        /// </summary>
        public static string SubHeading_Exporter {
            get {
                return ResourceManager.GetString("SubHeading_Exporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View, edit or delete a draft PRN.
        /// </summary>
        public static string SubHeading_Reprocessor {
            get {
                return ResourceManager.GetString("SubHeading_Reprocessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        public static string TableColumnDateCreated {
            get {
                return ResourceManager.GetString("TableColumnDateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string TableColumnMaterial {
            get {
                return ResourceManager.GetString("TableColumnMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERN number.
        /// </summary>
        public static string TableColumnNumber_Exporter {
            get {
                return ResourceManager.GetString("TableColumnNumber_Exporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRN number.
        /// </summary>
        public static string TableColumnNumber_Reprocessor {
            get {
                return ResourceManager.GetString("TableColumnNumber_Reprocessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent to.
        /// </summary>
        public static string TableColumnSentTo {
            get {
                return ResourceManager.GetString("TableColumnSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonnage.
        /// </summary>
        public static string TableColumnTonnage {
            get {
                return ResourceManager.GetString("TableColumnTonnage", resourceCulture);
            }
        }
    }
}
