//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPRN.Portal.Resources.PRNS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DraftConfirmationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DraftConfirmationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPRN.Portal.Resources.PRNS.DraftConfirmationResources", typeof(DraftConfirmationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ContinuePERN {
            get {
                return ResourceManager.GetString("ContinuePERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select if you are creating this PRN.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do want to do with this PRN?.
        /// </summary>
        public static string Heading {
            get {
                return ResourceManager.GetString("Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do want to do with this PRN?.
        /// </summary>
        public static string HeadingPERN {
            get {
                return ResourceManager.GetString("HeadingPERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save it as draft.
        /// </summary>
        public static string SaveItAsDraft {
            get {
                return ResourceManager.GetString("SaveItAsDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save it as draft.
        /// </summary>
        public static string SaveItAsDraftPERN {
            get {
                return ResourceManager.GetString("SaveItAsDraftPERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send it to:.
        /// </summary>
        public static string SendItTo {
            get {
                return ResourceManager.GetString("SendItTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send it to:.
        /// </summary>
        public static string SendItToPERN {
            get {
                return ResourceManager.GetString("SendItToPERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do want to do with this PRN?.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do want to do with this PRN?.
        /// </summary>
        public static string TitlePERN {
            get {
                return ResourceManager.GetString("TitlePERN", resourceCulture);
            }
        }
    }
}
