//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPRN.Portal.Resources.PRNS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PRNSTonnesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PRNSTonnesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPRN.Portal.Resources.PRNS.PRNSTonnesResources", typeof(PRNSTonnesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a PERN for:.
        /// </summary>
        public static string PERNCreateLabel {
            get {
                return ResourceManager.GetString("PERNCreateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many tonnes is this PERN for?.
        /// </summary>
        public static string PERNHowManyTonnesLabel {
            get {
                return ResourceManager.GetString("PERNHowManyTonnesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round this to the nearest whole tonne to determine the amount available for creating the PERN.
        /// </summary>
        public static string PERNRoundingLabel {
            get {
                return ResourceManager.GetString("PERNRoundingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonnage for this PERN.
        /// </summary>
        public static string PERNTitle {
            get {
                return ResourceManager.GetString("PERNTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a PRN for:.
        /// </summary>
        public static string PRNCreateLabel {
            get {
                return ResourceManager.GetString("PRNCreateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many tonnes is this PRN for?.
        /// </summary>
        public static string PRNHowManyTonnesLabel {
            get {
                return ResourceManager.GetString("PRNHowManyTonnesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round this to the nearest whole tonne to determine the amount available for creating the PRN.
        /// </summary>
        public static string PRNRoundingLabel {
            get {
                return ResourceManager.GetString("PRNRoundingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonnage for this PRN.
        /// </summary>
        public static string PRNTitle {
            get {
                return ResourceManager.GetString("PRNTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your waste balance is:.
        /// </summary>
        public static string WasteBalance {
            get {
                return ResourceManager.GetString("WasteBalance", resourceCulture);
            }
        }
    }
}
