//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPRN.Portal.Resources.PRNS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RequestCancelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RequestCancelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPRN.Portal.Resources.PRNS.RequestCancelResources", typeof(RequestCancelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel this PERN.
        /// </summary>
        public static string CancelButtonPERN {
            get {
                return ResourceManager.GetString("CancelButtonPERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel this PRN.
        /// </summary>
        public static string CancelButtonPRN {
            get {
                return ResourceManager.GetString("CancelButtonPRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can enter uo to 200 characters.
        /// </summary>
        public static string HintInfo {
            get {
                return ResourceManager.GetString("HintInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of the cancellation reason is 200 characters.
        /// </summary>
        public static string MaxLengthMessage {
            get {
                return ResourceManager.GetString("MaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This PERN has not yet been accepted.
        /// </summary>
        public static string NotAcceptedPERN {
            get {
                return ResourceManager.GetString("NotAcceptedPERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This PRN has not yet been accepted.
        /// </summary>
        public static string NotAcceptedPRN {
            get {
                return ResourceManager.GetString("NotAcceptedPRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to cancel this PERN.
        /// </summary>
        public static string PageHeadingPERN {
            get {
                return ResourceManager.GetString("PageHeadingPERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to cancel this PRN.
        /// </summary>
        public static string PageHeadingPRN {
            get {
                return ResourceManager.GetString("PageHeadingPRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to cancel PERN.
        /// </summary>
        public static string PageTitlePERN {
            get {
                return ResourceManager.GetString("PageTitlePERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to cancel PRN.
        /// </summary>
        public static string PageTitlePRN {
            get {
                return ResourceManager.GetString("PageTitlePRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add a reason for cancellation.
        /// </summary>
        public static string ReasonRequired {
            get {
                return ResourceManager.GetString("ReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why do you want to cancel this PERN?.
        /// </summary>
        public static string RequestQuestionPERN {
            get {
                return ResourceManager.GetString("RequestQuestionPERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why do you want to cancel this PRN?.
        /// </summary>
        public static string RequestQuestionPRN {
            get {
                return ResourceManager.GetString("RequestQuestionPRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If they agree to cancel, we&apos;ll ask {0} to approve your request..
        /// </summary>
        public static string RequestToCancelInfo2 {
            get {
                return ResourceManager.GetString("RequestToCancelInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has already accepted this PERN. We&apos;ll send them your cancellation request. They can either accept it or reject it..
        /// </summary>
        public static string RequestToCancelInfoPERN {
            get {
                return ResourceManager.GetString("RequestToCancelInfoPERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has already accepted this PRN. We&apos;ll send them your cancellation request. They can either accept it or reject it..
        /// </summary>
        public static string RequestToCancelInfoPRN {
            get {
                return ResourceManager.GetString("RequestToCancelInfoPRN", resourceCulture);
            }
        }
    }
}
