//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPRN.Portal.Resources.PRNS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewSentPrnResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewSentPrnResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPRN.Portal.Resources.PRNS.ViewSentPrnResources", typeof(ViewSentPrnResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting acceptance.
        /// </summary>
        public static string AwaitingAcceptance {
            get {
                return ResourceManager.GetString("AwaitingAcceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting cancellation.
        /// </summary>
        public static string AwaitingCancellation {
            get {
                return ResourceManager.GetString("AwaitingCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        public static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not found. Check the details and try again..
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by.
        /// </summary>
        public static string FilterBy {
            get {
                return ResourceManager.GetString("FilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View sent PERNs.
        /// </summary>
        public static string PernHeading {
            get {
                return ResourceManager.GetString("PernHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent PERNs.
        /// </summary>
        public static string PernTitle {
            get {
                return ResourceManager.GetString("PernTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View sent PRNs.
        /// </summary>
        public static string PrnHeading {
            get {
                return ResourceManager.GetString("PrnHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRN number.
        /// </summary>
        public static string PrnNumber {
            get {
                return ResourceManager.GetString("PrnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View sent PRN/PERNs.
        /// </summary>
        public static string PrnPernHeading {
            get {
                return ResourceManager.GetString("PrnPernHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent PRN/PERNs.
        /// </summary>
        public static string PrnPernTitle {
            get {
                return ResourceManager.GetString("PrnPernTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent PRNs.
        /// </summary>
        public static string PrnTitle {
            get {
                return ResourceManager.GetString("PrnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find PERN.
        /// </summary>
        public static string SearchPernBtn {
            get {
                return ResourceManager.GetString("SearchPernBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find PRN.
        /// </summary>
        public static string SearchPrnBtn {
            get {
                return ResourceManager.GetString("SearchPrnBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find PRN/PERN.
        /// </summary>
        public static string SearchPrnPernBtn {
            get {
                return ResourceManager.GetString("SearchPrnPernBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for a PRN by entering its number or the name of the company or compliance scheme you sent it to.
        /// </summary>
        public static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent to.
        /// </summary>
        public static string SentTo {
            get {
                return ResourceManager.GetString("SentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonnes.
        /// </summary>
        public static string Tonnes {
            get {
                return ResourceManager.GetString("Tonnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a PRN number to view, download or cancel it..
        /// </summary>
        public static string ViewDownloadCancelText {
            get {
                return ResourceManager.GetString("ViewDownloadCancelText", resourceCulture);
            }
        }
    }
}
