//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPRN.Portal.Resources.PRNS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewPRNResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewPRNResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPRN.Portal.Resources.PRNS.ViewPRNResources", typeof(ViewPRNResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Welsh]PRN Accepted.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Welsh]PRN Cancel requested.
        /// </summary>
        public static string CancellationRequested {
            get {
                return ResourceManager.GetString("CancellationRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Welsh]PRN Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Welsh]PRN Completed answers.
        /// </summary>
        public static string CheckYourAnswersComplete {
            get {
                return ResourceManager.GetString("CheckYourAnswersComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Welsh]PRN Created from waste received in December.
        /// </summary>
        public static string CreatedFromWasteDecemberLabel {
            get {
                return ResourceManager.GetString("CreatedFromWasteDecemberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Welsh]Date issued:.
        /// </summary>
        public static string DateIssuedLabel {
            get {
                return ResourceManager.GetString("DateIssuedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Welsh]PRN Created.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Welsh]history.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Welsh]Note.
        /// </summary>
        public static string NoteLabel {
            get {
                return ResourceManager.GetString("NoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Welsh]Packaging producer or compliance scheme.
        /// </summary>
        public static string ProducerOrComplianceLabel {
            get {
                return ResourceManager.GetString("ProducerOrComplianceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Welsh]PRN Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Welsh]PRN Sent completed.
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Welsh]Status.
        /// </summary>
        public static string StatusLabel {
            get {
                return ResourceManager.GetString("StatusLabel", resourceCulture);
            }
        }
    }
}
