//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portal.Resources.HomeResources", typeof(HomeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string DuringWhichMonth_April {
            get {
                return ResourceManager.GetString("DuringWhichMonth_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string DuringWhichMonth_August {
            get {
                return ResourceManager.GetString("DuringWhichMonth_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string DuringWhichMonth_December {
            get {
                return ResourceManager.GetString("DuringWhichMonth_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string DuringWhichMonth_February {
            get {
                return ResourceManager.GetString("DuringWhichMonth_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During which month was the waste received?.
        /// </summary>
        public static string DuringWhichMonth_Heading {
            get {
                return ResourceManager.GetString("DuringWhichMonth_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only record waste for this month and the months within an open quarterly return period..
        /// </summary>
        public static string DuringWhichMonth_HintText {
            get {
                return ResourceManager.GetString("DuringWhichMonth_HintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string DuringWhichMonth_January {
            get {
                return ResourceManager.GetString("DuringWhichMonth_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string DuringWhichMonth_July {
            get {
                return ResourceManager.GetString("DuringWhichMonth_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string DuringWhichMonth_June {
            get {
                return ResourceManager.GetString("DuringWhichMonth_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aluminium.
        /// </summary>
        public static string DuringWhichMonth_Label_Aluminium {
            get {
                return ResourceManager.GetString("DuringWhichMonth_Label_Aluminium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass.
        /// </summary>
        public static string DuringWhichMonth_Label_Glass {
            get {
                return ResourceManager.GetString("DuringWhichMonth_Label_Glass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper/board.
        /// </summary>
        public static string DuringWhichMonth_Label_Paper {
            get {
                return ResourceManager.GetString("DuringWhichMonth_Label_Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic.
        /// </summary>
        public static string DuringWhichMonth_Label_Plastic {
            get {
                return ResourceManager.GetString("DuringWhichMonth_Label_Plastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel.
        /// </summary>
        public static string DuringWhichMonth_Label_Steel {
            get {
                return ResourceManager.GetString("DuringWhichMonth_Label_Steel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood.
        /// </summary>
        public static string DuringWhichMonth_Label_Wood {
            get {
                return ResourceManager.GetString("DuringWhichMonth_Label_Wood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string DuringWhichMonth_March {
            get {
                return ResourceManager.GetString("DuringWhichMonth_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string DuringWhichMonth_May {
            get {
                return ResourceManager.GetString("DuringWhichMonth_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string DuringWhichMonth_November {
            get {
                return ResourceManager.GetString("DuringWhichMonth_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string DuringWhichMonth_October {
            get {
                return ResourceManager.GetString("DuringWhichMonth_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During which month was the waste received?.
        /// </summary>
        public static string DuringWhichMonth_PageTitle {
            get {
                return ResourceManager.GetString("DuringWhichMonth_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string DuringWhichMonth_September {
            get {
                return ResourceManager.GetString("DuringWhichMonth_September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Site_Continue {
            get {
                return ResourceManager.GetString("Site_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
