//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WasteTypesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WasteTypesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portal.Resources.WasteTypesResources", typeof(WasteTypesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aluminium.
        /// </summary>
        public static string aluminium {
            get {
                return ResourceManager.GetString("aluminium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass Other.
        /// </summary>
        public static string glass_other {
            get {
                return ResourceManager.GetString("glass-other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass Remelt.
        /// </summary>
        public static string glass_remelt {
            get {
                return ResourceManager.GetString("glass-remelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the material type?.
        /// </summary>
        public static string MaterialTypeOptionsTitle {
            get {
                return ResourceManager.GetString("MaterialTypeOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A material type requires to be selected.
        /// </summary>
        public static string MissingWasteTypeSelectionMessage {
            get {
                return ResourceManager.GetString("MissingWasteTypeSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper / Board.
        /// </summary>
        public static string paper_board {
            get {
                return ResourceManager.GetString("paper/board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper Composting.
        /// </summary>
        public static string paper_composting {
            get {
                return ResourceManager.GetString("paper-composting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic.
        /// </summary>
        public static string plastic {
            get {
                return ResourceManager.GetString("plastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel.
        /// </summary>
        public static string steel {
            get {
                return ResourceManager.GetString("steel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood.
        /// </summary>
        public static string wood {
            get {
                return ResourceManager.GetString("wood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood Composting.
        /// </summary>
        public static string wood_composting {
            get {
                return ResourceManager.GetString("wood-composting", resourceCulture);
            }
        }
    }
}
