//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WasteRecordCompleteResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WasteRecordCompleteResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portal.Resources.WasteRecordCompleteResources", typeof(WasteRecordCompleteResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is now active.
        /// </summary>
        public static string AccountIsActive {
            get {
                return ResourceManager.GetString("AccountIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go to my account.
        /// </summary>
        public static string AccountLink {
            get {
                return ResourceManager.GetString("AccountLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackLink {
            get {
                return ResourceManager.GetString("BackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ContinueButton {
            get {
                return ResourceManager.GetString("ContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Record Complete.
        /// </summary>
        public static string HomePage_Title {
            get {
                return ResourceManager.GetString("HomePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste record complete.
        /// </summary>
        public static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reference number.
        /// </summary>
        public static string ReferenceNumber {
            get {
                return ResourceManager.GetString("ReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new waste balance is.
        /// </summary>
        public static string WasteBalance {
            get {
                return ResourceManager.GetString("WasteBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tonnes.
        /// </summary>
        public static string WasteBalance2 {
            get {
                return ResourceManager.GetString("WasteBalance2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to do next.
        /// </summary>
        public static string WhatToDoNext {
            get {
                return ResourceManager.GetString("WhatToDoNext", resourceCulture);
            }
        }
    }
}
