//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WasteJourneyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WasteJourneyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portal.Resources.WasteJourneyResources", typeof(WasteJourneyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeLink {
            get {
                return ResourceManager.GetString("HomeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new users and manage your account.
        /// </summary>
        public static string HomePage_Account_Description {
            get {
                return ResourceManager.GetString("HomePage_Account_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new user.
        /// </summary>
        public static string HomePage_Account_Link_CreateUser {
            get {
                return ResourceManager.GetString("HomePage_Account_Link_CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account details.
        /// </summary>
        public static string HomePage_Account_Link_DetailUser {
            get {
                return ResourceManager.GetString("HomePage_Account_Link_DetailUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage a user.
        /// </summary>
        public static string HomePage_Account_Link_ManageUser {
            get {
                return ResourceManager.GetString("HomePage_Account_Link_ManageUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string HomePage_Account_Title {
            get {
                return ResourceManager.GetString("HomePage_Account_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply for accredidation, check your status and more.
        /// </summary>
        public static string HomePage_Accredidation_Description {
            get {
                return ResourceManager.GetString("HomePage_Accredidation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply for accredidation.
        /// </summary>
        public static string HomePage_Accredidation_Link_ApplyForAccredidation {
            get {
                return ResourceManager.GetString("HomePage_Accredidation_Link_ApplyForAccredidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My accredidations.
        /// </summary>
        public static string HomePage_Accredidation_Link_MyAccredidations {
            get {
                return ResourceManager.GetString("HomePage_Accredidation_Link_MyAccredidations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all applications.
        /// </summary>
        public static string HomePage_Accredidation_Link_ViewApplications {
            get {
                return ResourceManager.GetString("HomePage_Accredidation_Link_ViewApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accredidation.
        /// </summary>
        public static string HomePage_Accredidation_Title {
            get {
                return ResourceManager.GetString("HomePage_Accredidation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste - Home.
        /// </summary>
        public static string HomePage_Title {
            get {
                return ResourceManager.GetString("HomePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record your waste, manage your PRNs and submit your returns.
        /// </summary>
        public static string HomePage_WasteManagement_Description {
            get {
                return ResourceManager.GetString("HomePage_WasteManagement_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage a PRN.
        /// </summary>
        public static string HomePage_WasteManagement_Link_ManageAPrn {
            get {
                return ResourceManager.GetString("HomePage_WasteManagement_Link_ManageAPrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record waste.
        /// </summary>
        public static string HomePage_WasteManagement_Link_RecordWaste {
            get {
                return ResourceManager.GetString("HomePage_WasteManagement_Link_RecordWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit a return.
        /// </summary>
        public static string HomePage_WasteManagement_Link_SubmitAReturn {
            get {
                return ResourceManager.GetString("HomePage_WasteManagement_Link_SubmitAReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and edit records.
        /// </summary>
        public static string HomePage_WasteManagement_Link_ViewEditRecords {
            get {
                return ResourceManager.GetString("HomePage_WasteManagement_Link_ViewEditRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Management.
        /// </summary>
        public static string HomePage_WasteManagement_Title {
            get {
                return ResourceManager.GetString("HomePage_WasteManagement_Title", resourceCulture);
            }
        }
    }
}
