variables:
  azureSubscription: AZR-RWD-PRD1
  docker.imageName: protectivemonitoringapi
  acr.azureContainerRegistryName: prdrwdinfac1401
  acr.repositoryName: protectivemonitoringapirepository
  serviceName: prdrwdwebwa1403
